# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frankpy_MainWin.ui'
#
# Created: Mon Aug 13 13:54:23 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(910, 516)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(19, 11, 878, 444))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(379, 0))
        self.label.setMaximumSize(QtCore.QSize(379, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widget1 = QtGui.QWidget(self.widget)
        self.widget1.setMinimumSize(QtCore.QSize(491, 0))
        self.widget1.setMaximumSize(QtCore.QSize(491, 16777215))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout.addWidget(self.widget1, 0, 1, 4, 1)
        self.tableWidget = QtGui.QTableWidget(self.widget)
        self.tableWidget.setMinimumSize(QtCore.QSize(379, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(379, 16777215))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(379, 0))
        self.label_2.setMaximumSize(QtCore.QSize(379, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(self.widget)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(379, 0))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(379, 16777215))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuOpciones = QtGui.QMenu(self.menubar)
        self.menuOpciones.setObjectName(_fromUtf8("menuOpciones"))
        self.menuSalida = QtGui.QMenu(self.menubar)
        self.menuSalida.setObjectName(_fromUtf8("menuSalida"))
        self.menuCreditos = QtGui.QMenu(self.menubar)
        self.menuCreditos.setObjectName(_fromUtf8("menuCreditos"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_Muestra = QtGui.QAction(MainWindow)
        self.actionAbrir_Muestra.setObjectName(_fromUtf8("actionAbrir_Muestra"))
        self.actionSplines = QtGui.QAction(MainWindow)
        self.actionSplines.setObjectName(_fromUtf8("actionSplines"))
        self.actionCentrar = QtGui.QAction(MainWindow)
        self.actionCentrar.setObjectName(_fromUtf8("actionCentrar"))
        self.actionIntegrar = QtGui.QAction(MainWindow)
        self.actionIntegrar.setObjectName(_fromUtf8("actionIntegrar"))
        self.actionGuardar_Resultados = QtGui.QAction(MainWindow)
        self.actionGuardar_Resultados.setObjectName(_fromUtf8("actionGuardar_Resultados"))
        self.actionExportar_a = QtGui.QAction(MainWindow)
        self.actionExportar_a.setObjectName(_fromUtf8("actionExportar_a"))
        self.actionCreditos = QtGui.QAction(MainWindow)
        self.actionCreditos.setObjectName(_fromUtf8("actionCreditos"))
        self.actionBorrar_Muestra = QtGui.QAction(MainWindow)
        self.actionBorrar_Muestra.setObjectName(_fromUtf8("actionBorrar_Muestra"))
        self.menuArchivo.addAction(self.actionAbrir_Muestra)
        self.menuArchivo.addAction(self.actionBorrar_Muestra)
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.actionSplines)
        self.menuOpciones.addAction(self.actionCentrar)
        self.menuOpciones.addAction(self.actionIntegrar)
        self.menuSalida.addAction(self.actionGuardar_Resultados)
        self.menuSalida.addAction(self.actionExportar_a)
        self.menuCreditos.addAction(self.actionCreditos)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuOpciones.menuAction())
        self.menubar.addAction(self.menuSalida.menuAction())
        self.menubar.addAction(self.menuCreditos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "FrackPy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Valores Actuales de la Muestra", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Valores Procesados de la Muestra", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "Muestras", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpciones.setTitle(QtGui.QApplication.translate("MainWindow", "Opciones", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSalida.setTitle(QtGui.QApplication.translate("MainWindow", "Salida", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreditos.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_Muestra.setText(QtGui.QApplication.translate("MainWindow", "Cargar Muestra ..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSplines.setText(QtGui.QApplication.translate("MainWindow", "Splines", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCentrar.setText(QtGui.QApplication.translate("MainWindow", "Centrar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIntegrar.setText(QtGui.QApplication.translate("MainWindow", "Integrar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar_Resultados.setText(QtGui.QApplication.translate("MainWindow", "Guardar Gráficos y Tablas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportar_a.setText(QtGui.QApplication.translate("MainWindow", "Exportar a ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreditos.setText(QtGui.QApplication.translate("MainWindow", "Creditos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBorrar_Muestra.setText(QtGui.QApplication.translate("MainWindow", "Borrar Muestra ..", None, QtGui.QApplication.UnicodeUTF8))

